# Generated by Django 2.2.5 on 2019-10-09 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_calificaciones_docente_estudiante_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fecha', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Calificaciones',
        ),
        migrations.RenameField(
            model_name='docente',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='docente',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='docente',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='materia',
            old_name='Materia',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='docente',
            name='codigo',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='docente',
            name='facultad',
            field=models.CharField(default='Asignada', max_length=20),
        ),
        migrations.AddField(
            model_name='docente',
            name='honorarios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docente',
            name='materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Materia'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='acudiente',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='codigo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='direccion',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Materia'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='codigo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='facultad',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='calificacione',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Estudiante'),
        ),
    ]
