# Generated by Django 2.2.5 on 2019-10-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20191008_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacione',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='calificacione',
            name='estudiante',
            field=models.ManyToManyField(to='registro.Estudiante'),
        ),
    ]
