# Generated by Django 2.2.5 on 2019-10-10 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20191009_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='facultad',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='facultad',
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Docente')),
                ('materia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Materia')),
            ],
        ),
    ]
