# Generated by Django 2.2.5 on 2019-10-10 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_auto_20191010_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacione',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='calificacione',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Estudiante'),
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='materia',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='materia',
            field=models.ManyToManyField(to='registro.Materia'),
        ),
    ]
